### ISSUE TITLE
Error when unpacking a template into a specific directory

### ISSUE THREAD

**Issue by palsson** [Lundalogik/go_import#11]
```shell
C:\src\go-import\braintek
λ fruit_to_lime.bat unpack_template excel excel-2.3.1
Unpacking template excel to C:/src/go-import/braintek/excel-2.3.1
Making sure all needed gems are present
c:/ruby193/lib/ruby/gems/1.9.1/gems/fruit_to_lime-2.3.1/lib/fruit_to_lime/templating.rb:23:in `chdir': No such file or directory - C:/src/go-import/braintek/excel-2.3.1/excel (Errno::ENOENT)
        from c:/ruby193/lib/ruby/gems/1.9.1/gems/fruit_to_lime-2.3.1/lib/fruit_to_lime/templating.rb:23:in `unpack'
        from c:/ruby193/lib/ruby/gems/1.9.1/gems/fruit_to_lime-2.3.1/bin/fruit_to_lime:12:in `unpack_template'
        from c:/ruby193/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from c:/ruby193/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/ruby193/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/ruby193/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/ruby193/lib/ruby/gems/1.9.1/gems/fruit_to_lime-2.3.1/bin/fruit_to_lime:24:in `<top (required)>'
        from c:/Ruby193/bin/fruit_to_lime:23:in `load'
        from c:/Ruby193/bin/fruit_to_lime:23:in `<main>'
C:\src\go-import\braintek
```

But it will work if i don't specify the directory (excel-2.3.1)
```shell
C:\src\go-import\braintek
λ fruit_to_lime.bat unpack_template excel
Unpacking template excel to C:/src/go-import/braintek
Making sure all needed gems are present
C:\src\go-import\braintek
```
I don't know if this bug is specific just for the excel template or for all templates.

**Comment by palsson** [comment]
This is not relevant when working with sources.
