### ISSUE TITLE
Error if there is a hyperlink in a excel-document

### ISSUE THREAD

**Issue by ThinkFlipp** [Lundalogik/go_import#26]
If you are trying to convert an excel (.xlsx) file with the source "excel" you get an error if there is a hyperlink in the document. The error comes from inside Roo, however Roo should be able to manage hyperlinked-fields

Stack trace:

```
/usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/go_import-3.0.34/lib/go_import/roo_helper.rb:75:in `cell_to_csv': unhandled celltype link for cell at row: 2, col: 2 in sheet Medarbetare (RuntimeError)
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/go_import-3.0.34/lib/go_import/roo_helper.rb:44:in `block (2 levels) in rows_for_sheet'
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/go_import-3.0.34/lib/go_import/roo_helper.rb:43:in `upto'
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/go_import-3.0.34/lib/go_import/roo_helper.rb:43:in `block in rows_for_sheet'
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/go_import-3.0.34/lib/go_import/roo_helper.rb:41:in `upto'
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/go_import-3.0.34/lib/go_import/roo_helper.rb:41:in `rows_for_sheet'
	from /Users/fpe/Desktop/MyTestImport/.go_import/runner.rb:30:in `convert_source'
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/go_import-3.0.34/bin/go-import:83:in `run_import'
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/go_import-3.0.34/bin/go-import:192:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.0/bin/go-import:23:in `load'
	from /usr/local/var/rbenv/versions/2.1.0/bin/go-import:23:in `<main>'
```

**Comment by palsson** [comment]
I got the same error the other day and made a fix. Didn't know we had an open issue for it. 

I think we need to make a new release soon.
